- name: Check passenger source directory
  stat: path=~/passenger-{{ passenger.version }}
  register: passenger_source
- name: Extract passenger
  unarchive: src=http://s3.amazonaws.com/phusion-passenger/releases/passenger-{{ passenger.version }}.tar.gz dest=~ copy=no
  when: passenger_source.stat.exists == False
