- name: configure
  command: chdir={{apache_source_dir}} sh configure --with-included-apr
- name: compile
  command: chdir={{apache_source_dir}} make
- name: install
  command: chdir={{apache_source_dir}} make install
- include: cleanup.yml
