- name: update apt cache
  apt: update_cache=yes cache_valid_time=86400
  tab: ubuntu
- name: install package
  apt: name={{item}} state=present
  with_items: apache_packages
  when: ansible_pkg_mgr == 'apt'
  tag: ubuntu
