---
driver:
  name: vagrant

provisioner:
  name: ansible_playbook
  hosts: test-kitchen
  ansible_verbose: false
  ansible_velocity: 2

platforms:
  - name: ubuntu
    driver:
      box: "ubuntu/trusty64"
#  - name: centos-7.2

suites:
  - name: default
    run_list:
    attributes:
