- name: install build-essensial
  apt: name=build-essential state=present
  when: ansible_pkg_mgr == 'apt'
  tags: 
    - ubuntu
- name: install additional packages
  apt: name={{ item }} state=present
  with_items:
    - libpcre3-dev
    - openssl
    - libssl-dev
  when: ansible_pkg_mgr == 'apt'
  tags:
    - ubuntu
  # - name: download pip
  #   url_get: url="https://bootstrap.pypa.io/get-pip.py" dest=~
  # - name: install pip
  #   command: ch=~ python get-pip.py
  #   sudo: yes
