- name: install build-essensial
  apt: name=build-essential update_cache=yes
  become: true
  when: ansible_pkg_mgr == 'apt'
  tags: 
    - ubuntu
# - name: download pip
#   url_get: url="https://bootstrap.pypa.io/get-pip.py" dest=~
# - name: install pip
#   command: ch=~ python get-pip.py
#   sudo: yes
