- name: Include os-specific variables
  include_vars: "{{ ansible_os_family }}.yml"

- name: Define package variables
  set_fact:
    common_packages: "{{ __common_packages | list }}"
  when: common_packages is not defined

- include: "install-{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"
  # - name: download pip
  #   url_get: url="https://bootstrap.pypa.io/get-pip.py" dest=~
  # - name: install pip
  #   command: ch=~ python get-pip.py
  #   sudo: yes
